import { Luckiest_Guy } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const luckiestGuy = Luckiest_Guy({
  variable: "--font-luckiest-guy",
  subsets: ["latin"],
  weight: '400',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${luckiestGuy.variable} `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
